#!/usr/bin/env php
<?php

use Chaos\Monkey\Symfony\Tests\Symfony\Kernel;
use Symfony\Bundle\FrameworkBundle\Console\Application;

if (!is_file(__DIR__.'/../../vendor/autoload_runtime.php')) {
    throw new LogicException('Symfony Runtime is missing. Try running "composer require symfony/runtime".');
}

require_once __DIR__.'/../../vendor/autoload_runtime.php';

return function (array $context) {
    $kernel = new Kernel($context['APP_ENV'], (bool) $context['APP_DEBUG']);

    return new Application($kernel);
};
